<?php
namespace thunder;
use Medoo\Medoo;
class Model extends Medoo{
    protected $name = '';

    public $field='';

    public $where='';

    public $order='';

    public $limit='';

    public static $data_base_conf;

    public function __construct($name='',$data_base_conf=''){

        /*如果存在分组数据库配置则引入，否则使用配置*/
        $data_base_conf = (!empty($data_base_conf))?$data_base_conf:conf::get('database','MEDOO');
        if(!empty(self::$data_base_conf)) $data_base_conf = self::$data_base_conf;

        parent::__construct($data_base_conf);
        if(!empty($name)){
            $this->name   =  $name;
        }elseif(empty($this->name)){
            $this->name =   $this->getModelName();
        }
    }
    public function getModelName() {
        if(empty($this->name)){
            $name = get_class($this);
            if ( $pos = strrpos($name,'\\') ) {//有命名空间

                $this->name = substr($name,$pos+1);

            }else{

                $this->name = $name;
            }
        }

        return $this->name;
    }


    public function all(){
        $where = [];
        $field = '*';
        if($this->field!='') $field = $this->field;

        if(!empty($this->order)) $where['ORDER'] = $this->order;

        if(!empty($this->limit)) $where['LIMIT'] = $this->limit;

        if(!empty($this->where)) $where = array_merge($where,$this->where);

        $res = $this->select($this->name,$field,$where);
        return $res ;
    }
    /**
     * 根据ID查找一条数据
     */
    public function find($id='', $field = '*')
    {
        if(!is_array($field) && is_string($field)) $field = explode(',',$field);

        $where = [];
        if(empty($id) && empty($this->where)){
            $id = $this->min($this->name,'id');
            $where = ["id" => $id];
        }
        if(!empty($id)){
            $where = ["id" => $id];
        }
        if(!empty($this->where)) $where = array_merge($where,$this->where);
        if($this->field!='') $field = $this->field;
        if (count($field)==1) $field = $field[0];
        $data = $this->get($this->name, $field, $where);

        return $data;
    }

    /**
     * 新增数据
     */
    public function add($data)
    {
        return $this->insert($this->name, $data);
    }

    /**
     * 根据ID修改一条数据
     */
    public function setOne($id, $data)
    {
        return $this->update($this->name, $data, [
            'id' => $id
        ]);
    }

    /**
     * 根据ID删除一条数据
     */
    public function destroy($id)
    {
        return $this->delete($this->name, [
            'id' => $id
        ]);
    }
    /*
     * 清空数据表
     * */
    public function flushall(){
        $q = "delete  from ".$this->name;
        return $this->query($q);
    }


    public static function set_data_conf($data_base_conf=''){
        if(!empty($data_base_conf))
            self::$data_base_conf = $data_base_conf;
    }

    public function field($val){
        if(!is_array($val) && is_string($val)) $val = explode(',',$val);
        $this->field = $val;
        return $this;
    }

    public function where($val){
        $this->where = $val;
        return $this;
    }

    public function order($val){
        $this->order = $val;
        return $this;
    }
    public function limit($val){
        $this->limit = $val;
        return $this;
    }

    public function getLastId(){
        return $this->max($this->name,'id');
    }

    public function getFirstId(){
        return $this->min($this->name,'id');
    }

    public function count($table=null, $join = null, $column = null, $where = null)
    {
        return parent::count($this->name,$this->where); // TODO: Change the autogenerated stub
    }
}